name: steel_crypt
description: A comprehensive library of high-level, cryptographic APIs. This library supports hashing, password hashing,
  symmetric/asymmetric two-way encryption, and key/IV generation.
version: 1.6.1
homepage: https://github.com/AKushWarrior/steel_crypt
repository: https://github.com/AKushWarrior/steel_crypt
issue_tracker: https://github.com/AKushWarrior/steel_crypt/issues

executables:
  decrypt: decrypt
  encrypt: encrypt
  genkey: genkey
  hashtext: hashtext

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.5.2
  asn1lib: ^0.6.0

dev_dependencies:
  meta: any
  pedantic: any
  test: ^1.6.0
